
package com.ejb3.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldJAXWS", targetNamespace = "http://webservice.ejb3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldJAXWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initiate", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.Initiate")
    @ResponseWrapper(localName = "initiateResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.InitiateResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/initiateRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/initiateResponse")
    public void initiate();

    /**
     * 
     * @return
     *     returns java.util.List<com.ejb3.webservice.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.GetAllBooksResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/getAllBooksRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param author
     * @param id
     * @param title
     * @return
     *     returns com.ejb3.webservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.AddBookResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/addBookRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/addBookResponse")
    public Book addBook(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "title", targetNamespace = "")
        String title,
        @WebParam(name = "author", targetNamespace = "")
        String author);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.SayHelloResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/sayHelloRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
